### ISSUE TITLE
PHP 8 Support 

### ISSUE THREAD

**Issue by JukeI3ox** [Samson1964/contao-simplecolumns-bundle#1]
Hey,

wäre es möglich das Bundle zu updaten, so dass es auch mit PHP 8 funktioniert?

MfG

Sebastian

**Comment by Samson1964** [comment]
In der Version 1.0.1 (gerade hochgeladen) ist das gefixt.

**Comment by JukeI3ox** [comment]
Nice, vielen Dank.

Edit:
In der Composer.json müsste die PHP Version noch angepasst werden.^^
